CREATE TABLE mite_samples(
	sample_id	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	hive_id		VARCHAR(30) NOT NULL,
	collection_date	DATE NOT NULL,
	sample_period	INT UNSIGNED NOT NULL,
	num_mites	INT UNSIGNED NOT NULL,
	submit_time	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);